// Code generated by genx:doc@v0.3.9 DO NOT EDIT.
package installer

func (v *Agent) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}

func (v *Installer) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{"名称 如 cursor claude codex. 不指定则安装全部"}, true
		case "Path":
			return []string{"安装路径. 不指定则使用 Agent 默认路径; 仅可与 Name 同时使用"}, true
		case "Mode":
			return []string{"安装模式. 0: 项目级(当前路径) 1: 当前用户"}, true
		case "UpgradeToLatest":
			return []string{"是否更新最新go module依赖"}, true
		}
		return []string{}, false
	}
	return []string{"安装依赖skill"}, true
}

func (v *Version) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"打印skill版本"}, true
}

func (v *Info) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}
